CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    password_hash VARCHAR(200) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('Admin', 'Creator', 'Participant'))
);
CREATE TABLE IF NOT EXISTS quizzes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id INTEGER NOT NULL REFERENCES users(id),
    title VARCHAR(150) NOT NULL,
    category VARCHAR(80) NOT NULL,
    duration_seconds INTEGER NOT NULL CHECK (duration_seconds BETWEEN 10 AND 7200),
    status VARCHAR(20) NOT NULL CHECK (status IN ('Draft', 'Pending', 'Approved', 'Rejected')),
    review_note VARCHAR(500) NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS questions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id INTEGER NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    question_text VARCHAR(2000) NOT NULL,
    option_a VARCHAR(500) NOT NULL,
    option_b VARCHAR(500) NOT NULL,
    option_c VARCHAR(500) NOT NULL,
    option_d VARCHAR(500) NOT NULL,
    correct_answer INTEGER NOT NULL CHECK (correct_answer BETWEEN 0 AND 3),
    explanation VARCHAR(2000) NOT NULL,
    UNIQUE (quiz_id, position)
);
CREATE TABLE IF NOT EXISTS attempts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id INTEGER NOT NULL REFERENCES users(id),
    quiz_id INTEGER NOT NULL REFERENCES quizzes(id),
    quiz_title VARCHAR(150) NOT NULL,
    score INTEGER NOT NULL,
    total INTEGER NOT NULL CHECK (total > 0),
    time_used INTEGER NOT NULL,
    finished_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHECK (score BETWEEN 0 AND total)
);
CREATE TABLE IF NOT EXISTS answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id INTEGER NOT NULL REFERENCES attempts(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    question_text VARCHAR(2000) NOT NULL,
    options_text VARCHAR(2200) NOT NULL,
    selected_answer INTEGER NOT NULL CHECK (selected_answer BETWEEN -1 AND 3),
    correct_answer INTEGER NOT NULL CHECK (correct_answer BETWEEN 0 AND 3),
    explanation VARCHAR(2000) NOT NULL,
    UNIQUE (attempt_id, position)
);
